name: Test

on: [push, pull_request]

env:
    CARGO_INCREMENTAL: 0
    RUST_LOG: "debug"
    DIFF: 0
    RUST_MIN_STACK: 4194304

jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                rust:
                    - stable
                    - beta
                    - nightly
                    - 1.56

        steps:
            - uses: actions/checkout@v3

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ matrix.rust }}
                  override: true

            - run: cargo check --color always --all --all-targets
            - run: cargo clippy --color always --all --all-targets
            - run: cargo test --color always --all --all-targets
